name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
    # screen test
    - name: screen_test
      run: python ./test/unit_test/screen/screen_test.py
